name: Run PHP Script

on:
  schedule:
    - cron: '*/1 * * * *'  # Runs every minute

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1.10'  # Change to your required PHP version

    - name: Install PHP extensions
      run: sudo apt-get install -y php-curl

    - name: Install Composer
      run: |
        curl -sS https://getcomposer.org/installer | php
        sudo mv composer.phar /usr/local/bin/composer

    - name: Install Dependencies
      run: composer install

    - name: Run PHP script
      run: php index.php
